<?php
/**
 * Created by PhpStorm.
 * User: Rickard
 * Date: 2016-10-22
 * Time: 20:41
 */

namespace App\Utils;


use App\Models\User;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Support\Facades\Hash;

class Auth
{

    const TOKEN_VALID = 1, TOKEN_NOT_EXIST = 2, TOKEN_INVALID = 3;

    /**
     * Generate a key
     * @param $email string
     * @param $password string
     * @return string
     */
    public static function generateKey($email, $password) {
        $time = date_create()->getTimestamp();
        return Hash::make($email.$password.$time);
    }

    /**
     * Generate a token
     * @param $email string
     * @param $key string Key generated by Auth::generateKey()
     * @return string
     */
    public static function generateToken($email, $key) {
        $time = date_create()->getTimestamp();
        $payload = ['email' => $email, 'timestamp' => $time, 'key' => $key];
        return base64_encode(json_encode($payload));
    }

    /**
     * Get user from token
     * @param $token
     * @return int|User User if found, else error code
     */
    public static function checkToken($token) {
        $payload = json_decode(base64_decode($token));
        if (is_object($payload)) {
            if ($user = User::where('token', $payload->key)->first()) {
                return $user;
            } else {
                return Auth::TOKEN_NOT_EXIST;
            }
        } else {
            return Auth::TOKEN_INVALID;
        }
    }

    /**
     * Check if token is associated with any user in list
     * @param $token string The token to check
     * @param $list Collection List of users
     * @return bool
     */
    public static function userMemberOf($token, $list) {
        $payload = json_decode(base64_decode($token));
        $auth = false;
        foreach ($list as $player) {
            if ($player->token === $payload->key) {
                $auth = true;
                break;
            }
        }
        return $auth;
    }

}